---
apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  containers:
  - name: node-exporter
    image: quay.io/prometheus/node-exporter
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  #  annotations:
          #    prometheus.io/scrape: 'true'
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30091
  type: NodePort
