global:
  resolve_timeout: 5m
route:
  group_by: ['job','service','cluster']
  group_wait: 2m
  group_interval: 3m
  repeat_interval: 4m
  receiver: default
  routes:
         - match:
            severity: critical
           receiver: my_mail
receivers:
- name: default
- name: my_mail
  slack_configs:
    - api_url: "https://talk.gigaset-devnet.pl/hooks/geu8yf6dp3njfgikp7josw3sto"
      username: "OPS"
