---
apiVersion: v1
kind: Pod
metadata:
  name: hello-counter
  namespace: monitoring
  labels:
    app: hello
spec:
  containers:
  - name: hello-counter
    image: swiechkamil/counter:1
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
