{
 "title": "Kubernetes / Nodes / Custom",
 "tags": [ "kubernetes-custom" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Opened descriptors (%) by GNET apps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum without (endpoint,namespace) (process_files_open_files / process_files_max_files) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Opened descriptors (%) by pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " sum without (namespace,endpoint,instance,service) (process_open_fds / process_max_fds) *100"
    }
   ]
  },
  {
   "title": "Nodes conditions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"Ready\",status=\"true\"})"
    },
    {
     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    },
    {
     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    },
    {
     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"})"
    }
   ]
  }
 ]
}