---
apiVersion: v1
kind: Pod
metadata:
  name: hello-bucket
  namespace: monitoring
  labels:
    app: hello
spec:
  containers:
  - name: hello-bucket
    image: swiechkamil/bucket:1
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: monitoring
spec:
  selector:
    app: hello
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: server
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
  type: NodePort
