apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: hello-counter
        image: swiechkamil/counter:1
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        ports:
        - containerPort: 8000
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: monitoring
spec:
  selector:
    app: counter
  ports:
    - name: metrics
      protocol: TCP 
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: server
      protocol: TCP 
      port: 8001
      targetPort: 8001
      nodePort: 30081
  type: NodePort
