apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prometheus-operator
  name: nodes-grafana-dashboard
  labels:
     grafana_dashboard: "1"
data:
   nodes-custom.json: |-
           {
             "annotations": {
               "list": [
                 {
                   "builtIn": 1,
                   "datasource": "-- Grafana --",
                   "enable": true,
                   "hide": true,
                   "iconColor": "rgba(0, 211, 255, 1)",
                   "name": "Annotations & Alerts",
                   "type": "dashboard"
                 }
               ]
             },
             "editable": true,
             "gnetId": null,
             "graphTooltip": 0,
             "links": [],
             "panels": [
               {
                 "aliasColors": {},
                 "bars": false,
                 "dashLength": 10,
                 "dashes": false,
                 "datasource": null,
                 "fill": 1,
                 "fillGradient": 0,
                 "gridPos": {
                   "h": 8,
                   "w": 12,
                   "x": 0,
                   "y": 0
                 },
                 "id": 5,
                 "interval": "",
                 "legend": {
                   "alignAsTable": true,
                   "avg": false,
                   "current": true,
                   "max": true,
                   "min": false,
                   "show": true,
                   "total": false,
                   "values": true
                 },
                 "lines": true,
                 "linewidth": 1,
                 "nullPointMode": "null",
                 "options": {
                   "dataLinks": []
                 },
                 "percentage": false,
                 "pointradius": 2,
                 "points": false,
                 "renderer": "flot",
                 "seriesOverrides": [],
                 "spaceLength": 10,
                 "stack": false,
                 "steppedLine": false,
                 "targets": [
                   {
                     "expr": "sum without (endpoint,namespace) (process_files_open_files / process_files_max_files) *100",
                     "legendFormat": "{{pod}}",
                     "refId": "A"
                   }
                 ],
                 "thresholds": [],
                 "timeFrom": null,
                 "timeRegions": [],
                 "timeShift": null,
                 "title": "Opened descriptors (%) by GNET apps",
                 "tooltip": {
                   "shared": true,
                   "sort": 0,
                   "value_type": "individual"
                 },
                 "type": "graph",
                 "xaxis": {
                   "buckets": null,
                   "mode": "time",
                   "name": null,
                   "show": true,
                   "values": []
                 },
                 "yaxes": [
                   {
                     "format": "percent",
                     "label": null,
                     "logBase": 1,
                     "max": null,
                     "min": null,
                     "show": true
                   },
                   {
                     "format": "short",
                     "label": null,
                     "logBase": 1,
                     "max": null,
                     "min": null,
                     "show": true
                   }
                 ],
                 "yaxis": {
                   "align": false,
                   "alignLevel": null
                 }
               },
               {
                 "aliasColors": {},
                 "bars": false,
                 "dashLength": 10,
                 "dashes": false,
                 "datasource": null,
                 "fill": 1,
                 "fillGradient": 0,
                 "gridPos": {
                   "h": 8,
                   "w": 12,
                   "x": 12,
                   "y": 0
                 },
                 "id": 4,
                 "legend": {
                   "alignAsTable": true,
                   "avg": false,
                   "current": true,
                   "max": true,
                   "min": false,
                   "show": true,
                   "total": false,
                   "values": true
                 },
                 "lines": true,
                 "linewidth": 1,
                 "nullPointMode": "null",
                 "options": {
                   "dataLinks": []
                 },
                 "percentage": false,
                 "pointradius": 2,
                 "points": false,
                 "renderer": "flot",
                 "seriesOverrides": [],
                 "spaceLength": 10,
                 "stack": false,
                 "steppedLine": false,
                 "targets": [
                   {
                     "expr": " sum without (namespace,endpoint,instance,service) (process_open_fds / process_max_fds) *100",
                     "legendFormat": "",
                     "refId": "A"
                   }
                 ],
                 "thresholds": [],
                 "timeFrom": null,
                 "timeRegions": [],
                 "timeShift": null,
                 "title": "Opened descriptors (%) by pod",
                 "tooltip": {
                   "shared": true,
                   "sort": 0,
                   "value_type": "individual"
                 },
                 "type": "graph",
                 "xaxis": {
                   "buckets": null,
                   "mode": "time",
                   "name": null,
                   "show": true,
                   "values": []
                 },
                 "yaxes": [
                   {
                     "format": "percent",
                     "label": null,
                     "logBase": 1,
                     "max": null,
                     "min": null,
                     "show": true
                   },
                   {
                     "format": "short",
                     "label": null,
                     "logBase": 1,
                     "max": null,
                     "min": null,
                     "show": true
                   }
                 ],
                 "yaxis": {
                   "align": false,
                   "alignLevel": null
                 }
               },
               {
                 "columns": [],
                 "datasource": null,
                 "fontSize": "100%",
                 "gridPos": {
                   "h": 7,
                   "w": 24,
                   "x": 0,
                   "y": 8
                 },
                 "id": 2,
                 "links": [],
                 "options": {},
                 "pageSize": null,
                 "scroll": true,
                 "showHeader": true,
                 "sort": {
                   "col": 0,
                   "desc": true
                 },
                 "styles": [
                   {
                     "alias": "Time",
                     "dateFormat": "YYYY-MM-DD HH:mm:ss",
                     "pattern": "Time",
                     "type": "hidden"
                   },
                   {
                     "alias": "Ready",
                     "colorMode": "cell",
                     "colors": [
                       "rgba(245, 54, 54, 0.9)",
                       "#37872D",
                       "rgba(50, 172, 45, 0.97)"
                     ],
                     "dateFormat": "YYYY-MM-DD HH:mm:ss",
                     "decimals": 2,
                     "mappingType": 1,
                     "pattern": "Value #A",
                     "thresholds": [
                       "0.9"
                     ],
                     "type": "number",
                     "unit": "short"
                   },
                   {
                     "alias": "Disk Pressure",
                     "colorMode": "cell",
                     "colors": [
                       "rgba(50, 172, 45, 0.97)",
                       "rgba(237, 129, 40, 0.89)",
                       "rgba(245, 54, 54, 0.9)"
                     ],
                     "dateFormat": "YYYY-MM-DD HH:mm:ss",
                     "decimals": 2,
                     "mappingType": 1,
                     "pattern": "Value #B",
                     "thresholds": [
                       "1"
                     ],
                     "type": "number",
                     "unit": "short"
                   },
                   {
                     "alias": "Memory Pressure",
                     "colorMode": "cell",
                     "colors": [
                       "rgba(50, 172, 45, 0.97)",
                       "rgba(237, 129, 40, 0.89)",
                       "rgba(245, 54, 54, 0.9)"
                     ],
                     "dateFormat": "YYYY-MM-DD HH:mm:ss",
                     "decimals": 2,
                     "mappingType": 1,
                     "pattern": "Value #C",
                     "thresholds": [
                       "1"
                     ],
                     "type": "number",
                     "unit": "short"
                   },
                   {
                     "alias": "PID Pressure",
                     "colorMode": "cell",
                     "colors": [
                       "rgba(50, 172, 45, 0.97)",
                       "rgba(237, 129, 40, 0.89)",
                       "rgba(245, 54, 54, 0.9)"
                     ],
                     "dateFormat": "YYYY-MM-DD HH:mm:ss",
                     "decimals": 2,
                     "mappingType": 1,
                     "pattern": "Value #D",
                     "thresholds": [
                       "1"
                     ],
                     "type": "number",
                     "unit": "short"
                   },
                   {
                     "alias": "",
                     "colorMode": null,
                     "colors": [
                       "rgba(50, 172, 45, 0.97)",
                       "rgba(237, 129, 40, 0.89)",
                       "rgba(245, 54, 54, 0.9)"
                     ],
                     "decimals": 2,
                     "pattern": "/.*/",
                     "thresholds": [],
                     "type": "number",
                     "unit": "short"
                   }
                 ],
                 "targets": [
                   {
                     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
                     "format": "table",
                     "instant": true,
                     "intervalFactor": 1,
                     "legendFormat": "",
                     "refId": "A"
                   },
                   {
                     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
                     "format": "table",
                     "instant": true,
                     "intervalFactor": 1,
                     "legendFormat": "",
                     "refId": "B"
                   },
                   {
                     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
                     "format": "table",
                     "instant": true,
                     "intervalFactor": 1,
                     "legendFormat": "",
                     "refId": "C"
                   },
                   {
                     "expr": "sum without(__name__,endpoint,job,instance,namespace,pod,service,condition,status)(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"})",
                     "format": "table",
                     "instant": true,
                     "intervalFactor": 1,
                     "legendFormat": "",
                     "refId": "D"
                   }
                 ],
                 "timeFrom": null,
                 "timeShift": null,
                 "title": "Nodes conditions",
                 "transform": "table",
                 "type": "table"
               }
             ],
             "schemaVersion": 20,
             "style": "dark",
             "tags": [
               "kubernetes-custom"
             ],
             "templating": {
               "list": []
             },
             "time": {
               "from": "now-6h",
               "to": "now"
             },
             "timepicker": {
               "refresh_intervals": [
                 "5s",
                 "10s",
                 "30s",
                 "1m",
                 "5m",
                 "15m",
                 "30m",
                 "1h",
                 "2h",
                 "1d"
               ],
               "time_options": [
                 "5m",
                 "15m",
                 "1h",
                 "6h",
                 "12h",
                 "24h",
                 "2d",
                 "7d",
                 "30d"
               ]
             },
             "timezone": "",
             "title": "Kubernetes / Nodes / Custom",
             "uid": "nodes-custom",
             "version": 1
           }
