apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJywnc2VydmljZScsJ2NsdXN0ZXInXQogIGdyb3VwX3dhaXQ6IDJtCiAgZ3JvdXBfaW50ZXJ2YWw6IDNtCiAgcmVwZWF0X2ludGVydmFsOiA0bQogIHJlY2VpdmVyOiBkZWZhdWx0CiAgcm91dGVzOgogICAgICAgICAtIG1hdGNoOgogICAgICAgICAgICBzZXZlcml0eTogY3JpdGljYWwKICAgICAgICAgICByZWNlaXZlcjogbWF0dGVybW9zdAogICAgICAgICAtIG1hdGNoOgogICAgICAgICAgICBzZXZlcml0eTogd2FybmluZwogICAgICAgICAgIHJlY2VpdmVyOiBtYXR0ZXJtb3N0CnJlY2VpdmVyczoKLSBuYW1lOiBkZWZhdWx0Ci0gbmFtZTogbWF0dGVybW9zdAogIHNsYWNrX2NvbmZpZ3M6CiAgICAgLSBhcGlfdXJsOiAiaHR0cHM6Ly90YWxrLmdpZ2FzZXQtZGV2bmV0LnBsL2hvb2tzL2dldTh5ZjZkcDNuamZnaWtwN2pvc3czc3RvIgp0ZW1wbGF0ZXM6CiAgICAgICAgIC0gJy9ldGMvYWxlcnRtYW5hZ2VyL2NvbmZpZ21hcHMvYWxlcnRtYW5hZ2VyLXRlbXBsYXRlLyoudG1wbCcK
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-config
