global:
  resolve_timeout: 5m
route:
  group_by: ['job','service']
  group_wait: 2m
  group_interval: 10m
  repeat_interval: 12h
  receiver: default
  routes:
         - match:
            severity: critical
           receiver: my_mail
receivers:
- name: default
- name: my_mail
  email_configs:
  - to: 'kamil.swiechowski.ext@gigaset.com'
