---
alertmanager:
  alertmanagerSpec:
    configSecret: "alertmanager-config"
  service:
    nodePort: 30093
    type: NodePort
    port: 9093
    targetPort: 9093
grafana:
  service:
    nodePort: 30800
    port: 3000
    targetPort: 3000
    type: NodePort
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
prometheus:
  service:
    nodePort: 30090
    type: NodePort
  prometheusSpec:
    enableAdminAPI: true
    externalLabels:
       cluster: kind
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 400Mi
prometheus-node-exporter:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 32Mi
prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
