apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: pop-prometheus-operator-prometheus
    app: prometheus
    release: pop
  name: pop-prometheus-operator-cutom-apps-2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/type: custom-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
      - port: metrics
        path: /
        relabelings:
          - sourceLabels: ["__meta_kubernetes_pod_node_name"]
            targetLabel: "node"
            regex: "kind-(.*)"
            replacement: "$1"
            action: "replace"
