---
apiVersion: v1
kind: Pod
metadata:
  name: hello-labels
  namespace: monitoring
  labels:
    app: hello
    app.kubernetes.io/type: custom-app
spec:
  containers:
  - name: hello-labels
    image: swiechkamil/labels:1
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: monitoring
  labels:
    app.kubernetes.io/type: custom-app
spec:
  selector:
    app: hello
    app.kubernetes.io/type: custom-app
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: server
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
  type: NodePort
