apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: pop-prometheus-operator-prometheus
    role: alert-rules
    app: prometheus-operator
    release: pop
  name: prometheus-nodes-rules
spec:
  groups:
    - name: ./my-custom-rules
      rules:
      - record: instance:node_network_received_bytes:rate:sum
        expr: sum by(instance) (rate(node_network_receive_bytes_total[3m]))
    - name: ./my-custom-alerts
      rules:
      - alert: instance:node_network_received_bytes:rate:sum:high
        expr: instance:node_network_received_bytes:rate:sum > 10000
        for: 1m
        labels:
           severity: critical
        annotations:
           description: Node network recived bytes {{ printf "%.4g" $value  }}.
