---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
grafana:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 100Mi
prometheus:
  service:
    nodePort: 30090
    type: NodePort
  prometheusSpec:
    externalLabels:
       cluster: kind
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 400Mi
  additionalServiceMonitors: 
    - name: "pop-prometheus-operator-custom-apps"
      selector:
        matchLabels:
          app.kubernetes.io/type: custom-app      
      namespaceSelector:
        matchNames: 
          - gnet
      endpoints: 
        - port: http
          path: /
prometheus-node-exporter:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 32Mi
prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
